name: Ubuntu build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure container
      run: sudo apt-get install -y gcc cmake make

    - name: Build app
      run: |
       cd src/server
       cmake -DCMAKE_CXX_FLAGS="-DDEBUG" -DBUILD_WITH_TESTS=ON .
       make

    - name: Run tests
      run: |
       cd src/server/tests
       make
       chmod a+x ./unit_tests
       ./unit_tests
       

